### ISSUE TITLE
:sparkles: boutons aube / crépuscule

### ISSUE THREAD

**Issue by Khaali-dev** [Dellatosa/trinites#1]
Ajouter un bouton aube (remet au max le karma lumiere et le karma-adam s'il est de type lumière) et un bouton crépuscule (remet au max le karma Ténèbres et le karma-adam s'il est Ténèbres)

**Comment by Qaw** [comment]
Uniquement pour les trinités ?

**Comment by Khaali-dev** [comment]
#1.0.0

**Comment by Khaali-dev** [comment]
Résolu 1.0.0
